### ISSUE TITLE
Add GitHub Actions to auto-deploy on push

### ISSUE THREAD

**Issue by asiakay** [asiakay/bridge-link-page#12]
```yaml
# .github/workflows/deploy.yml
name: Deploy to GitHub Pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploying to GitHub Pages..."
      ```
