### ISSUE TITLE
The 10%-opacity background image is barely visible

### ISSUE THREAD

**Issue by asiakay** [asiakay/bridge-link-page#17]
Increase opacity to 0.2–0.3 or add a subtle CSS blur() to make it more discernible

```css
#background-image {
  filter: blur(1px) brightness(0.8);
  opacity: 0.3;
}
```
