### ISSUE TITLE
Make the background image slowly pan/zoom for a "hyperspace" effect

### ISSUE THREAD

**Issue by asiakay** [asiakay/bridge-link-page#23]
```css
#background-image {
  animation: float 30s infinite alternate ease-in-out;
}
@keyframes float {
  0% { transform: scale(1) translateX(0); }
  100% { transform: scale(1.1) translateX(5%); }
}
```
